---
- name: Allow traffic on ports 22, 80, and 443
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Enable ufw & set incoming policy to 'drop'
  community.general.ufw:
    direction: incoming
    policy: deny
    state: enabled
